---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xds
data:
  listeners: |
    - name: foo
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10001
      filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
              cluster: foo
              stat_prefix: foo
    - name: bar
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10002
      filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
              cluster: bar
              stat_prefix: bar

  clusters: |
    - name: foo
      type: EDS
      connect_timeout: 0.25s
      eds_cluster_config:
        service_name: default/foo
        eds_config:
          api_config_source:
            api_type: REST
            cluster_names: [xds_cluster]
            refresh_delay: 1s
    - name: bar
      type: EDS
      connect_timeout: 0.25s
      eds_cluster_config:
        service_name: default/bar
        eds_config:
          api_config_source:
            api_type: REST
            cluster_names: [xds_cluster]
            refresh_delay: 1s

  assignments: |
    by-cluster:
      foo:
        listeners:
          - foo
        clusters:
          - foo
      bar:
        listeners:
          - bar
        clusters:
          - bar
    by-node-id:
      foo:
        listeners:
          - foo
        clusters:
          - foo
      bar:
        listeners:
          - bar
        clusters:
          - bar
